version: '3.8'

services:

  web:
    build: .
    environment:
      FLASK_CONFIG: production
      FLASK_ENV: production
      MONGO_URI: mongodb://mongo:27017/miniUrlDB
    ports:
      - "5001:5000"
    volumes:
      - .:/opt
    links:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

volumes:
  mongo-data:
  mongo-configdb:
